# GeoNetwork
#
# Access via "http://localhost:8080/geonetwork" (or "http://$(docker-machine ip):8080/geonetwork" if using docker-machine)
#
# Default user: admin
# Default password: admin

version: '3.4'
services:

  geonetwork:
    image: geonetwork:postgres
    restart: unless-stopped
    container_name: core4geonetwork
    ports:
      - "8080:8080"
    environment:
      DATA_DIR: /var/lib/geonetwork_data
      POSTGRES_DB_HOST: db4geonetwork
      POSTGRES_DB_USERNAME: geonetwork
      POSTGRES_DB_PASSWORD: geonetwork
    depends_on:
      - postgres
    volumes:
      - geonetwork:/var/lib/geonetwork_data

# the db container
  postgres:
    image: mdillon/postgis
    restart: unless-stopped
    container_name: db4geonetwork
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: geonetwork
      POSTGRES_USER: geonetwork
    volumes:
      - postgres:/var/lib/postgresql/data

# geoserver container
  geoserver:
    image: kartoza/geoserver:2.13.0
    container_name: geoserver4geonetwork
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    environment:
      GEOSERVER_DATA_DIR: geonetwork
      GEOWEBCACHE_CACHE_DIR: geonetwork
    volumes:
      - geoserver:/opt/geoserver/data_dir

volumes:
  geonetwork:
    name: data-geonetwork
  geoserver:
    name: data-geoserver
  postgres:
    name: data-postgres